### ISSUE TITLE
Not downloadable lecture 6 video

### ISSUE THREAD

**Issue by pitmonticone** [mitmath/6S083#3]
The [lecture 6 video](https://mit.zoom.us/rec/share/2tV7C66r2jhObKPs1WbcZqInRa3ZX6a8gyVL_aZbyUkq9TEEKy-uFAPg0XBUN6gF) doesn't seem to be downloadable. 

Thank you so much for sharing this wonderful educational material.

**Comment by alanedelman** [comment]
It should be
![image](https://user-images.githubusercontent.com/862530/81354674-41b58580-909a-11ea-8c17-84e8627c2533.png)

try again?

**Comment by pitmonticone** [comment]
I'm sorry, I should have written [lecture 5](https://mit.zoom.us/rec/play/upwtIbqr-G03SdyR4wSDVP5wW42_KP-s1XQb-fYMmUrjUiEGOwWiM7oWNubLaoSfoeTNffbV9z7JRv9G?continueMode=true&_x_zm_rtaid=EjZnETzOTAuXSMfnyq7NAQ.1588921643270.59c6499b3ce8ff55a638395b884af911&_x_zm_rhtaid=766). 

<img width="1224" alt="Screenshot 2020-05-08 at 09 08 52" src="https://user-images.githubusercontent.com/38562595/81380814-c5f42100-910b-11ea-998b-e6ccd993223f.png">

Thanks again.
